name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    env:
      Solution_Name: palc

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Dependencies
      run: dotnet restore ${{env.Solution_Name}}

    - name: Build
      run: dotnet build ${{env.Solution_Name}} --configuration Release --no-restore

    - name: Zip Release
      uses: TheDoctor0/zip-release@0.7.6
      with:
        # Filename for archive
        filename: release.zip # default is release.zip
        # Base path for archive files
        path: . # optional, default is .
        # Working directory before zipping
        directory: ${{ env.Solution_Name }}\bin\Release # optional, default is .
          
    # Upload the MSIX package: https://github.com/marketplace/actions/upload-a-build-artifact
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ZIP
        path: ${{ env.Solution_Name }}\bin\Release\release.zip
